apiVersion: v1
kind: PersistentVolume
metadata:
  name: hf-pv-oss
  labels:
    alicloud-pvname: hf-pv-oss
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ossplugin.csi.alibabacloud.com
    volumeHandle: ollama-pv-oss
    nodePublishSecretRef:
      name: oss-secret
      namespace: default
    volumeAttributes:
      bucket: "denverdino-model-test"
      url: "oss-ap-southeast-1-internal.aliyuncs.com"
      otherOpts: "-o max_stat_cache_size=0 -o allow_other -o kernel_cache -o retries=5"
      path: "/huggingface"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-pvc-oss
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      alicloud-pvname: hf-pv-oss
